//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _001WcfTestClient.ServiceStreamReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceStreamReference.IServiceStream")]
    public interface IServiceStream {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStream/Invoke", ReplyAction="http://tempuri.org/IServiceStream/InvokeResponse")]
        System.IO.Stream Invoke(System.IO.Stream clientStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStream/Invoke", ReplyAction="http://tempuri.org/IServiceStream/InvokeResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> InvokeAsync(System.IO.Stream clientStream);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceStreamChannel : _001WcfTestClient.ServiceStreamReference.IServiceStream, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceStreamClient : System.ServiceModel.ClientBase<_001WcfTestClient.ServiceStreamReference.IServiceStream>, _001WcfTestClient.ServiceStreamReference.IServiceStream {
        
        public ServiceStreamClient() {
        }
        
        public ServiceStreamClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceStreamClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStreamClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStreamClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream Invoke(System.IO.Stream clientStream) {
            return base.Channel.Invoke(clientStream);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> InvokeAsync(System.IO.Stream clientStream) {
            return base.Channel.InvokeAsync(clientStream);
        }
    }
}
